import {Branch} from '../types/branch';

export const MIRI_LOCATION = {
  latitude: 4.3995,
  longitude: 113.9914,
};

export const MOCK_BRANCHES: Branch[] = [
  {
    id: '1',
    name: 'HS Coffee Bintang Megamall',
    address: 'Lot G.01, Ground Floor, Bintang Megamall, Miri',
    latitude: 4.4005,
    longitude: 113.992,
    openTime: '08:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '2',
    name: 'HS Coffee Boulevard',
    address: 'Boulevard Shopping Complex, Jalan Pujut, Miri',
    latitude: 4.415,
    longitude: 114.015,
    openTime: '09:00 AM',
    closeTime: '10:30 PM',
  },
  {
    id: '3',
    name: 'HS Coffee Imperial City',
    address: 'Imperial City Mall, Jalan Merpati, Miri',
    latitude: 4.398,
    longitude: 113.991,
    openTime: '08:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '4',
    name: 'HS Coffee Lutong',
    address: 'Jalan Pasar Lutong, Lutong, Miri',
    latitude: 4.475,
    longitude: 114.005,
    openTime: '07:30 AM',
    closeTime: '09:00 PM',
  },
  {
    id: '5',
    name: 'HS Coffee Senadin',
    address: 'Senadin Gateway, Miri',
    latitude: 4.512,
    longitude: 114.018,
    openTime: '08:00 AM',
    closeTime: '11:00 PM',
  },
  {
    id: '6',
    name: 'HS Coffee Marina ParkCity',
    address: 'Marina Square 1, Marina ParkCity, Miri',
    latitude: 4.395,
    longitude: 113.985,
    openTime: '08:00 AM',
    closeTime: '12:00 AM',
  },
  {
    id: '7',
    name: 'HS Coffee Pelita',
    address: 'Pelita Commercial Centre, Miri',
    latitude: 4.408,
    longitude: 113.998,
    openTime: '07:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '8',
    name: 'HS Coffee Permyjaya',
    address: 'Permy Mall, Bandar Baru Permyjaya, Miri',
    latitude: 4.445,
    longitude: 114.025,
    openTime: '09:00 AM',
    closeTime: '10:00 PM',
  },
  {
    id: '9',
    name: 'HS Coffee Luak Esplanade',
    address: 'Luak Bay, Miri',
    latitude: 4.345,
    longitude: 113.97,
    openTime: '08:00 AM',
    closeTime: '11:00 PM',
  },
  {
    id: '10',
    name: 'HS Coffee Krokop',
    address: 'Jalan Krokop Utama, Miri',
    latitude: 4.412,
    longitude: 114.008,
    openTime: '06:30 AM',
    closeTime: '06:00 PM',
  },
];
